### ISSUE TITLE
How does this work internally?

### ISSUE THREAD

**Issue by Selbi182** [yanorei32/obs-spotify-bridge#206]
Hey! This isn't an issue, I'm just really curious about this project and how it works. I'm also working on a Spotify player app and I never managed to figure out how to get song changes in real time. The only solution I ever thought of was polling the Spotify API over and over.

You would help me immensely if you could explain how this app manages to get its data in real time!

**Comment by yanorei32** [comment]
When I searched, Spotify's API documentation didn't have a near real-time currently playing information API.
But Discord was using it.
I simulated the behavior of a Discord client and implemented it.

**Comment by Selbi182** [comment]
Thank you! Can you tell me how often you need to refresh the Discord token?

**Comment by yanorei32** [comment]
Discord does not refresh tokens.
All tokens have a very long lifespan.
It will persist unless you change your password, set up two-factor authentication, etc.

I think, it's not good for security but it's convenient for this case.

**Comment by Selbi182** [comment]
Perfect, then I will implement this in my app with Discord as well. Thank you so much, your source code has been immensely helpful!
